[package]
name = "aws-sdk-ecs-demo"
version = "0.1.0"
edition = "2021"

[dependencies]
aws-config = "1"
aws-sdk-ecs = "1"
color-eyre = "0.6"
tokio = { version = "1", features= ["full"] }
thiserror = "2"
